### ISSUE TITLE
Push replication didn't happen until app was opened

### ISSUE THREAD

**Issue by tleyden** [tleyden/office-radar#1]
Today @waynecarter @zgramana were picked up by the beacon, however their geofence events were not pushed up to the server until they opened the app.  Once they opened the app, their old geofence events from hours ago were pushed up to the sync gateway.

I haven't had a chance to look at their logs yet, but was just wondering if anyone had any ideas or documentation references?

**Comment by npomfret** [comment]
Does anyone know how to un-suspend the replicators?  I've tried the following but the list of replicators is always empty for my db (even thou I have 2 running):

```
-(void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)notification fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler {
  NSLog(@"notification-body => %@", notification);

  NSMutableArray *toSuspend = [NSMutableArray array];

  CBLManager *manager = [CBLManager sharedInstance];
  for (NSString* name in [manager allDatabaseNames]) {
    CBLDatabase* db = [manager databaseNamed:name error:nil];
    NSArray* replications = [db allReplications];
    for(CBLReplication* rep in replications) {
      if(rep.suspended) {
        [rep setSuspended: NO];
        [toSuspend addObject: rep];
      }
    }
  }

  [RCTPushNotificationManager didReceiveRemoteNotification:notification];

  dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(20 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
    NSLog(@"notification-complete => %@", notification);
    for(CBLReplication* rep in toSuspend) {
      [rep setSuspended: YES];
    }

    completionHandler(UIBackgroundFetchResultNewData);
  });
}
```

**Comment by snej** [comment]
@npomfret Is this a bug in Office Radar?

**Comment by npomfret** [comment]
No

I think I understand the issue now. The replication tasks are started from the REST API and are not available via the `[db allReplications]` call.   I've added a feature request: https://github.com/couchbase/couchbase-lite-ios/issues/1410

**Comment by tleyden** [comment]
Thanks for the issue report!  Closing since it doesn't seem to be specific to office radar
